import type { Metadata } from 'next'
import './globals.css'
import { Flex } from 'antd'
import ScriptLoader from 'next/script'

export const metadata: Metadata = {
  title: 'Files box',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ScriptLoader src="/iconfont/iconfont.js"></ScriptLoader>
      </head>
      <body>
        <Flex vertical={true} className="main-container-wrap">
          <div className="main-container">{children}</div>
        </Flex>
      </body>
    </html>
  )
}
